services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - dataprotection:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=useless_inventions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  dataprotection:
